-- USE DB_SCE

SELECT count(*) FROM DB_SCE.Escola.TB_ESCOLA 
SELECT * FROM CONVENIO..TB_SITUACAO_CONVENIO

1a. condição
SELECT * FROM DB_SCE.Escola.TB_ESCOLA 
	WHERE		CNPJ_DA_APM IS NOT NULL 
			AND NR_CONVE_FDE_APM IS NULL AND CD_SITUACAO = 1 AND CD_REDE_ENSINO = 1 AND CD_TP_IDENTIFICADOR IN (3,8,10,31,36)
-- 1 REGS

2a. condição
SELECT * FROM DB_SCE.Escola.TB_ESCOLA 
	WHERE		CNPJ_DA_APM IS NOT NULL 
			AND NR_CONVE_FDE_APM IS NOT NULL 
			AND CD_REDE_ENSINO = 1 
			AND CD_TP_IDENTIFICADOR IN (3,8,10,31,36)
-- 7335 REGS



------------------------------------------------------------------------------------------------------------------------------------------------
-- 7335 LINHAS
SELECT DISTINCT
	DI.NOME_DIRET	AS DIRETORIA
	,ES.CD_ESCOLA	AS CIE
	,ES.NR_CONVE_FDE_APM	AS COD_APM
	,ES.CNPJ_DA_APM	AS CNPJ
	,ES.NM_APM		AS APM
	,SC.NM_SITUACAO	AS SITUACAO_CONVENIO

	,CASE 
		WHEN SA.FLG_REGULAR = 1 THEN 'NÃO'
		WHEN SA.FLG_REGULAR = 0 THEN 'SIM'
		ELSE ''
	END
	AS POSSUI_IMPEDIMENTO

FROM DB_SCE.Escola.TB_ESCOLA ES
LEFT JOIN CONVENIO..TB_SITUACAO_CONVENIO	SC ON SC.ID_SITUACAO_CONVENIO = ES.ID_SITUACAO_CONVENIO
INNER JOIN DESENV..DIRETORIA				DI ON DI.COD_DIRETORIA = ES.CD_DIRETORIA
LEFT JOIN CONVENIO..TB_CONVENIO				CV ON ES.NR_CONVE_FDE_APM = CV.COD_APM
LEFT JOIN CONVENIO..TB_SITUACAO_APM			SA ON SA.COD_APM = CV.COD_APM
WHERE		ES.CNPJ_DA_APM IS NOT NULL		
		AND ES.NR_CONVE_FDE_APM IS NOT NULL 
		AND ES.CD_REDE_ENSINO = 1 
		AND ES.CD_TP_IDENTIFICADOR IN (3,8,10,31,36)
		-- AND ES.ID_SITUACAO_CONVENIO = 1; -- ATIVO 


------- RELAÇÃO CONVENIADAS ----------------RELATÓRIO DO SISTEMA


SELECT DISTINCT
	DI.NOME_DIRET	AS DIRETORIA
	,ES.CD_ESCOLA	AS CIE
	,CV.COD_APM		AS COD_APM
	,ES.NM_COMPLETO_ESCOLA	AS ESCOLA
	,ES.NM_APM		AS APM
	,ES.CNPJ_DA_APM	AS CNPJ
	
	, (SELECT TOP 1 CO.EMAIL_ADMIN_GEST  FROM DB_SCE.ESCOLA.TB_CONTATO CO
		WHERE CO.CD_CONTATO = CT.CD_CONTATO )  AS EMAIL

	,(SELECT TOP 1('('+CO.DDD + ')' + ' ' + CO.NR_TELEFONE)  FROM DB_SCE.ESCOLA.TB_CONTATO CO
		WHERE CO.CD_CONTATO IN (CO.CD_CONTATO) AND  CT.CD_ESCOLA = ES.CD_ESCOLA    )  AS TELEFONE
	 
	-- Dados CC --
	,BANCO = (ISNULL(CC.DS_BANCO,'') + ' - ' + ISNULL(CC.NM_BANCO,''))
	,AGENCIA = (ISNULL(CC.DS_AGENCIA,'') + '-' + ISNULL(CC.NR_DIGITO_AGENCIA,'') )
	,CONTA = (ISNULL(CC.DS_CONTA,'') + '-' + ISNULL(CC.NR_DIGITO_CONTA,''))

	,FU.DS_SITUACAO	AS SIT_FUNC_ESCOLA
	
	,CASE 
		WHEN SA.FLG_REGULAR = 1 THEN 'NÃO'
		WHEN SA.FLG_REGULAR = 0 THEN 'SIM'
		ELSE ''
	END
	AS POSSUI_IMPEDIMENTO

	,SC.NM_SITUACAO	AS SITUACAO_CONVENIO

		FROM DB_SCE.ESCOLA.TB_ESCOLA				ES
		LEFT JOIN CONVENIO..TB_CONVENIO				CV ON ES.NR_CONVE_FDE_APM = CV.COD_APM
		INNER JOIN DB_SCE.ESCOLA.TB_SITUACAO_FUNCIONAMENTO FU ON FU.CD_SITUACAO = ES.CD_SITUACAO
		LEFT JOIN CONVENIO..TB_CONTA_CORRENTE		CC ON CC.COD_APM = CV.COD_APM AND CC.FL_STATUS = 1
		INNER JOIN DESENV..DIRETORIA				DI ON DI.COD_DIRETORIA = ES.CD_DIRETORIA
		LEFT JOIN CONVENIO..TB_SITUACAO_APM			SA ON SA.COD_APM = CV.COD_APM
		LEFT JOIN DB_SCE.ESCOLA.TB_CONTATO_UNIDADE	CT ON CT.CD_ESCOLA = ES.CD_ESCOLA
		LEFT JOIN DB_SCE.ESCOLA.TB_CONTATO			CO ON CO.CD_CONTATO = CT.CD_CONTATO AND CO.IC_TELEFONE_PRINCIPAL = 1
		LEFT JOIN CONVENIO..TB_SITUACAO_CONVENIO	SC ON SC.ID_SITUACAO_CONVENIO = ES.ID_SITUACAO_CONVENIO
		WHERE	
				ES.CNPJ_DA_APM IS NOT NULL		
				AND ES.NR_CONVE_FDE_APM IS NOT NULL 
				AND ES.CD_REDE_ENSINO = 1 
				AND ES.CD_TP_IDENTIFICADOR IN (3,8,10,31,36)
				--AND ES.ID_SITUACAO_CONVENIO = 1 -- ATIVO
		ORDER BY DI.NOME_DIRET,CV.COD_APM ;



--RODADNDO
                            
                SELECT DISTINCT
				 ES.CD_ESCOLA	AS CIE
					,DI.NOME_DIRET	AS DIRETORIA
					,ES.CD_DIRETORIA
	                ,ES.ID_SITUACAO_CONVENIO
	                ,CV.COD_APM		AS COD_APM
	                ,ES.NM_COMPLETO_ESCOLA	AS ESCOLA
	                ,ES.NM_APM		AS APM
	                ,ES.CNPJ_DA_APM	AS CNPJ
                    ,ES.ID_SITUACAO_CONVENIO ID_SITUACAO_CONVENIO
	                , lower(CO.EMAIL_ADMIN_GEST) AS EMAIL
	                ,'('+CO.DDD + ')' + ' ' + CO.NR_TELEFONE AS TELEFONE
	                ,BANCO = (ISNULL(CC.DS_BANCO,'') + ' - ' + ISNULL(CC.NM_BANCO,''))
	                ,AGENCIA = (ISNULL(CC.DS_AGENCIA,'') + '-' + ISNULL(CC.NR_DIGITO_AGENCIA,'') )
	                ,CONTA = (ISNULL(CC.DS_CONTA,'') + '-' + ISNULL(CC.NR_DIGITO_CONTA,''))
	                ,FU.DS_SITUACAO	AS SIT_FUNC_ESCOLA
	                ,CASE 
		                WHEN SA.FLG_REGULAR = 1 THEN 'NÃO'
		                WHEN SA.FLG_REGULAR = 0 THEN 'SIM'
		                ELSE ''
	                END
	                AS POSSUI_IMPEDIMENTO
		                ,CASE 
		                WHEN ES.ID_SITUACAO_CONVENIO = 1 THEN 'ATIVO'
		                WHEN ES.ID_SITUACAO_CONVENIO = 2 THEN 'INATIVO'
		                WHEN ES.ID_SITUACAO_CONVENIO = 3 THEN 'SUSPENSO'
		                WHEN ES.ID_SITUACAO_CONVENIO = 4 THEN 'EM CADASTRAMENTO'
		                ELSE ''
	                END
	                AS SITUACAO_CONVENIO

                FROM DB_SCE.ESCOLA.TB_ESCOLA				ES
                LEFT JOIN CONVENIO..TB_CONVENIO				CV ON ES.NR_CONVE_FDE_APM = CV.COD_APM
                INNER JOIN DB_SCE.ESCOLA.TB_SITUACAO_FUNCIONAMENTO FU ON FU.CD_SITUACAO = ES.CD_SITUACAO
                INNER JOIN CONVENIO..TB_CONTA_CORRENTE		CC ON CC.COD_APM = CV.COD_APM AND CC.FL_STATUS = 1
                INNER JOIN DESENV..DIRETORIA				DI ON DI.COD_DIRETORIA = ES.CD_DIRETORIA
                LEFT JOIN CONVENIO..TB_SITUACAO_APM			SA ON SA.COD_APM = CV.COD_APM
                LEFT JOIN DB_SCE.ESCOLA.TB_CONTATO_UNIDADE	CT ON CT.CD_ESCOLA = ES.CD_ESCOLA
                INNER JOIN DB_SCE.ESCOLA.TB_CONTATO			CO ON CO.CD_CONTATO = CT.CD_CONTATO AND CO.IC_TELEFONE_PRINCIPAL = 1
                LEFT JOIN CONVENIO..TB_SITUACAO_CONVENIO	SC ON SC.ID_SITUACAO_CONVENIO = ES.ID_SITUACAO_CONVENIO
                WHERE		ES.CNPJ_DA_APM IS NOT NULL		
		        AND ES.NR_CONVE_FDE_APM IS NOT NULL 
		        AND ES.CD_REDE_ENSINO = 1 
		        AND ES.CD_TP_IDENTIFICADOR IN (3,8,10,31,36)  
				ORDER BY DI.NOME_DIRET,CV.COD_APM ;




-- **************************relatorio do convenio ***************************************

				SELECT 
				DI.COD_DIRETORIA
				,DI.NOME_DIRET	AS	 DIRETORIA
				,ES.CD_ESCOLA	AS CIE
				,CV.COD_APM		AS COD_APM
				,ES.NM_APM		AS APM
				,convert(varchar(10),CV.DATA_INICIO ,103)	AS INICIO_VIGENCIA
				,convert(varchar(10),CV.DATA_FIM,103)		AS FIM_VIGENCIA

				,CV.QTDE_ALUNO
				,VALOR = (FC.VLR_PER_CAPITA * CV.QTDE_ALUNO)
				,ST.NM_SITUACAO		AS SITUACAO_TC
	
				,CASE 
					WHEN SA.FLG_REGULAR = 1 THEN 'NÃO'
					WHEN SA.FLG_REGULAR = 0 THEN 'SIM'
					ELSE ''
				END
				AS POSSUI_IMPEDIMENTO

				,CASE 
					WHEN ES.ID_SITUACAO_CONVENIO = 1 THEN 'ATIVO'
					WHEN ES.ID_SITUACAO_CONVENIO = 2 THEN 'INATIVO'
					WHEN ES.ID_SITUACAO_CONVENIO = 3 THEN 'SUSPENSO'
					WHEN ES.ID_SITUACAO_CONVENIO = 4 THEN 'EM CADASTRAMENTO'
					ELSE ''
				END
				AS SITUACAO_CONVENIO

				,CASE 
					WHEN CV.FLG_VIGENTE = 1 THEN 'SIM'
					WHEN CV.FLG_VIGENTE = 0 THEN 'NÃO'
					ELSE ''
				END
				AS VIGENTE	
				,SA.FLG_REGULAR
				,ES.ID_SITUACAO_CONVENIO
				,CV.FLG_VIGENTE
			FROM CONVENIO..TB_CONVENIO CV 
			INNER JOIN DB_SCE.ESCOLA.TB_ESCOLA		ES ON ES.NR_CONVE_FDE_APM = CV.COD_APM
			INNER JOIN DESENV..DIRETORIA			DI ON DI.COD_DIRETORIA = ES.CD_DIRETORIA
			LEFT JOIN CONVENIO..TB_SITUACAO_APM		SA ON SA.COD_APM = CV.COD_APM
			INNER JOIN CONVENIO..TB_TERMO_CONVENIO	TC ON TC.COD_TERMO_CONVENIO = CV.COD_TERMO_CONVENIO
			INNER JOIN CONVENIO..TB_FORMA_CALCULO	FC ON FC.COD_FORMA_CALCULO = TC.COD_FORMA_CALCULO
			INNER JOIN CONVENIO..TB_SITUACAO_TCE	ST ON ST.COD_SITUACAO_TCE = CV.COD_SITUACAO_TCE
			WHERE CV.FLG_ATIVO = 1 AND CV.FLG_EXCLUSAO = 0 AND CV.FLG_VIGENTE  = 1
			ORDER BY DI.NOME_DIRET,CV.COD_APM



--*****************************************************************************************************************
-- report convenio
				declare @CODAPM int = 323 ;
				declare @COD_APM int = 323;
				declare @COD_CONVENIO int = 0;
				declare @COD_ESCOLA int = 0;
				declare @ANO_INICIO int = 0;
			    declare @ANO_FIM int = 0 ;            
			
			
                             SELECT 
	                            D.COD_DIRETORIA
	                            ,D.NOME_DIRET	AS	 DIRETORIA
	                            ,ES.CD_ESCOLA	AS CIE
	                            ,CONV.COD_APM		AS COD_APM
	                            ,ES.NM_APM		AS APM
	                            ,convert(varchar(10),CONV.DATA_INICIO ,103)	AS INICIO_VIGENCIA
	                            ,convert(varchar(10),CONV.DATA_FIM,103)		AS FIM_VIGENCIA

	                            ,CONV.QTDE_ALUNO
	                            ,VALOR = (FC.VLR_PER_CAPITA * CONV.QTDE_ALUNO)
	                            ,ST.NM_SITUACAO		AS SITUACAO_TC
	                            ,SA.FLG_REGULAR
	                            ,ES.ID_SITUACAO_CONVENIO
	                            ,CONV.FLG_VIGENTE
	                            ,CASE 
		                            WHEN SA.FLG_REGULAR = 1 THEN 'NÃO'
		                            WHEN SA.FLG_REGULAR = 0 THEN 'SIM'
		                            ELSE ''
	                            END
	                            AS POSSUI_IMPEDIMENTO
	                            ,CASE 
		                            WHEN ES.ID_SITUACAO_CONVENIO = 1 THEN 'ATIVO'
		                            WHEN ES.ID_SITUACAO_CONVENIO = 2 THEN 'INATIVO'
		                            WHEN ES.ID_SITUACAO_CONVENIO = 3 THEN 'SUSPENSO'
		                            WHEN ES.ID_SITUACAO_CONVENIO = 4 THEN 'EM CADASTRAMENTO'
		                            ELSE ''
	                            END
	                            AS SITUACAO_CONVENIO

	                            ,CASE 
		                            WHEN CONV.FLG_VIGENTE = 1 THEN 'SIM'
		                            WHEN CONV.FLG_VIGENTE = 0 THEN 'NÃO'
		                            ELSE ''
	                            END
	                            AS VIGENTE	
                            FROM CONVENIO..TB_CONVENIO CONV 
                            INNER JOIN DB_SCE.ESCOLA.TB_ESCOLA		ES ON ES.NR_CONVE_FDE_APM = CONV.COD_APM
                            INNER JOIN DESENV..DIRETORIA			D ON D.COD_DIRETORIA = ES.CD_DIRETORIA
                            LEFT JOIN CONVENIO..TB_SITUACAO_APM		SA ON SA.COD_APM = CONV.COD_APM
                            INNER JOIN CONVENIO..TB_TERMO_CONVENIO	TC ON TC.COD_TERMO_CONVENIO = CONV.COD_TERMO_CONVENIO
                            INNER JOIN CONVENIO..TB_FORMA_CALCULO	FC ON FC.COD_FORMA_CALCULO = TC.COD_FORMA_CALCULO
                            INNER JOIN CONVENIO..TB_SITUACAO_TCE	ST ON ST.COD_SITUACAO_TCE = CONV.COD_SITUACAO_TCE
                            WHERE   CONV.FLG_ATIVO = 1 
                                    AND CONV.FLG_EXCLUSAO = 0 
                          
                              AND CONV.COD_APM = @CODAPM  AND CONV.FLG_VIGENTE IN ( 1 )   ORDER BY D.NOME_DIRET,CONV.COD_APM ;



							  --**************************************************************************
							  --report conveniada

			
                            
                
	SELECT DISTINCT
	DI.NOME_DIRET	AS DIRETORIA
	,ES.CD_ESCOLA	AS CIE
	,CV.COD_APM		AS COD_APM
	,ES.NM_COMPLETO_ESCOLA	AS ESCOLA
	,ES.NM_APM		AS APM
	,ES.CNPJ_DA_APM	AS CNPJ
	
	, (SELECT TOP 1 CO.EMAIL_ADMIN_GEST  FROM DB_SCE.ESCOLA.TB_CONTATO CO
	inner join  DB_SCE.ESCOLA.TB_CONTATO_UNIDADE CT on CO.CD_CONTATO = CT.CD_CONTATO
		WHERE CO.CD_CONTATO = CT.CD_CONTATO AND  CT.CD_ESCOLA = ES.CD_ESCOLA    )  AS EMAIL

	,(SELECT TOP 1('('+CO.DDD + ')' + ' ' + CO.NR_TELEFONE)  FROM DB_SCE.ESCOLA.TB_CONTATO CO
		inner join  DB_SCE.ESCOLA.TB_CONTATO_UNIDADE CT on CO.CD_CONTATO = CT.CD_CONTATO
		WHERE CO.CD_CONTATO = CT.CD_CONTATO AND  CT.CD_ESCOLA = ES.CD_ESCOLA    )  AS TELEFONE
	 
	-- Dados CC --
	,BANCO = (ISNULL(CC.DS_BANCO,'') + ' - ' + ISNULL(CC.NM_BANCO,''))
	,AGENCIA = (ISNULL(CC.DS_AGENCIA,'') + '-' + ISNULL(CC.NR_DIGITO_AGENCIA,'') )
	,CONTA = (ISNULL(CC.DS_CONTA,'') + '-' + ISNULL(CC.NR_DIGITO_CONTA,''))

	,FU.DS_SITUACAO	AS SIT_FUNC_ESCOLA
	
	,CASE 
		WHEN SA.FLG_REGULAR = 1 THEN 'NÃO'
		WHEN SA.FLG_REGULAR = 0 THEN 'SIM'
		ELSE ''
	END
	AS POSSUI_IMPEDIMENTO

	,SC.NM_SITUACAO	AS SITUACAO_CONVENIO

		FROM DB_SCE.ESCOLA.TB_ESCOLA				ES
		LEFT JOIN CONVENIO..TB_CONVENIO				CV ON ES.NR_CONVE_FDE_APM = CV.COD_APM
		INNER JOIN DB_SCE.ESCOLA.TB_SITUACAO_FUNCIONAMENTO FU ON FU.CD_SITUACAO = ES.CD_SITUACAO
		LEFT JOIN CONVENIO..TB_CONTA_CORRENTE		CC ON CC.COD_APM = CV.COD_APM AND CC.FL_STATUS = 1
		INNER JOIN DESENV..DIRETORIA				DI ON DI.COD_DIRETORIA = ES.CD_DIRETORIA
		LEFT JOIN CONVENIO..TB_SITUACAO_APM			SA ON SA.COD_APM = CV.COD_APM
		LEFT JOIN DB_SCE.ESCOLA.TB_CONTATO_UNIDADE	CT ON CT.CD_ESCOLA = ES.CD_ESCOLA
		LEFT JOIN DB_SCE.ESCOLA.TB_CONTATO			CO ON CO.CD_CONTATO = CT.CD_CONTATO AND CO.IC_TELEFONE_PRINCIPAL = 1
		LEFT JOIN CONVENIO..TB_SITUACAO_CONVENIO	SC ON SC.ID_SITUACAO_CONVENIO = ES.ID_SITUACAO_CONVENIO
		WHERE		ES.CNPJ_DA_APM IS NOT NULL		
				AND ES.NR_CONVE_FDE_APM IS NOT NULL 
				AND ES.CD_REDE_ENSINO = 1 
				AND ES.CD_TP_IDENTIFICADOR IN (3,8,10,31,36) ORDER BY DI.NOME_DIRET,CV.COD_APM  ;
				


				SELECT TOP 1 * FROM DB_SCE.ESCOLA.TB_CONTATO_UNIDADE	CT ;

				SELECT TOP 1 * FROM DB_SCE.ESCOLA.TB_CONTATO	CO ;

				SELECT TOP 1 CO.EMAIL_ADMIN_GEST AS EMAIL FROM DB_SCE.ESCOLA.TB_CONTATO CO
					-- WHERE CO.CD_CONTATO = CT.CD_CONTATO

			SELECT TOP 1 ('('+CO.DDD + ')' + ' ' + CO.NR_TELEFONE) AS TELEFONE  FROM DB_SCE.ESCOLA.TB_CONTATO CO   
			
			
		
		--*************************************
		-- conveniada cado ativo


                            

                            
                
SELECT DISTINCT
	DI.NOME_DIRET	AS DIRETORIA
	,ES.CD_ESCOLA	AS CIE
	,CV.COD_APM		AS COD_APM
	,ES.NM_COMPLETO_ESCOLA	AS ESCOLA
	,ES.NM_APM		AS APM
	,ES.CNPJ_DA_APM	AS CNPJ
	
	, (SELECT TOP 1 CO.EMAIL_ADMIN_GEST  FROM DB_SCE.ESCOLA.TB_CONTATO CO
	inner join  DB_SCE.ESCOLA.TB_CONTATO_UNIDADE CT on CO.CD_CONTATO = CT.CD_CONTATO
		WHERE CO.CD_CONTATO = CT.CD_CONTATO AND  CT.CD_ESCOLA = ES.CD_ESCOLA    )  AS EMAIL

	,(SELECT TOP 1('('+CO.DDD + ')' + ' ' + CO.NR_TELEFONE)  FROM DB_SCE.ESCOLA.TB_CONTATO CO
		inner join  DB_SCE.ESCOLA.TB_CONTATO_UNIDADE CT on CO.CD_CONTATO = CT.CD_CONTATO
		WHERE CO.CD_CONTATO = CT.CD_CONTATO AND  CT.CD_ESCOLA = ES.CD_ESCOLA    )  AS TELEFONE
	
	,BANCO = (ISNULL(CC.DS_BANCO,'') + ' - ' + ISNULL(CC.NM_BANCO,''))
	,AGENCIA = (ISNULL(CC.DS_AGENCIA,'') + '-' + ISNULL(CC.NR_DIGITO_AGENCIA,'') )
	,CONTA = (ISNULL(CC.DS_CONTA,'') + '-' + ISNULL(CC.NR_DIGITO_CONTA,''))

	,FU.DS_SITUACAO	AS SIT_FUNC_ESCOLA
	
	,CASE 
		WHEN SA.FLG_REGULAR = 1 THEN 'NÃO'
		WHEN SA.FLG_REGULAR = 0 THEN 'SIM'
		ELSE ''
	END
	AS POSSUI_IMPEDIMENTO

	,SC.NM_SITUACAO	AS SITUACAO_CONVENIO

		FROM DB_SCE.ESCOLA.TB_ESCOLA				ES
		LEFT JOIN CONVENIO..TB_CONVENIO				CV ON ES.NR_CONVE_FDE_APM = CV.COD_APM
		INNER JOIN DB_SCE.ESCOLA.TB_SITUACAO_FUNCIONAMENTO FU ON FU.CD_SITUACAO = ES.CD_SITUACAO
		LEFT JOIN CONVENIO..TB_CONTA_CORRENTE		CC ON CC.COD_APM = CV.COD_APM AND CC.FL_STATUS = 1
		INNER JOIN DESENV..DIRETORIA				DI ON DI.COD_DIRETORIA = ES.CD_DIRETORIA
		LEFT JOIN CONVENIO..TB_SITUACAO_APM			SA ON SA.COD_APM = CV.COD_APM
		LEFT JOIN DB_SCE.ESCOLA.TB_CONTATO_UNIDADE	CT ON CT.CD_ESCOLA = ES.CD_ESCOLA
		LEFT JOIN DB_SCE.ESCOLA.TB_CONTATO			CO ON CO.CD_CONTATO = CT.CD_CONTATO AND CO.IC_TELEFONE_PRINCIPAL = 1
		LEFT JOIN CONVENIO..TB_SITUACAO_CONVENIO	SC ON SC.ID_SITUACAO_CONVENIO = ES.ID_SITUACAO_CONVENIO
		WHERE		ES.CNPJ_DA_APM IS NOT NULL		
				AND ES.NR_CONVE_FDE_APM IS NOT NULL 
				AND ES.CD_REDE_ENSINO = 1 
				AND ES.CD_TP_IDENTIFICADOR IN (3,8,10,31,36) ORDER BY DI.NOME_DIRET,CV.COD_APM ;