--RICARDO AUGUSTO ROSA CARVALHEIRO

USE CESUH;

select * from tb_candidato where nr_cpf ='22035587840'; -- Eli '05505157980' ; //  26690587878  // dani 21324801840 só 2

select * from tb_candidato where nm_candidato like 'CARLOS EDUARDO BARNETT'; -- cd_candidato  = 9344570;

select * from tb_nota where cd_candidato = 9864074 order by CD_CONCURSO; -- Eli 9344570 ; 8800329

SELECT top 10 * from CESUH.DBO.TB_CANDIDATO_CONCURSO CCON  where cd_candidato =  1302575; -- 9344570 ;

select top 10 * from CESUH.DBO.TB_CONCURSO TC ;

SELECT TOP 10 * FROM CESUH.DBO.TB_CERTIFICADO CER 
INNER JOIN  CESUH.DBO.TB_CANDIDATO_CONCURSO CCON 
ON CCON.CD_CANDIDATO = CER.CD_CANDIDATO 
AND CCON.CD_CONCURSO = CER.CD_CONCURSO 
AND CCON.CD_CANDIDATO = 9088587 ;


-- INNER JOIN CESUH.DBO.TB_CERTIFICADO CER ON CCON.CD_CANDIDATO = CER.CD_CANDIDATO AND CCON.CD_CONCURSO = CER.CD_CONCURSO



Declare @NM_CANDIDATO varchar = 'ROSA CARVALHEIRO';

SELECT  distinct (CCON.CD_CONCURSO),  TC.DS_CONCURSO,  CAN.CD_CANDIDATO,  CAN.NM_CANDIDATO,  
CAN.NM_MAE_CANDIDATO,  CAN.NR_RG,  CAN.SG_ORGAO_RG,  CAN.SG_UF_RG,  CAN.EN_CANDIDATO,  
CAN.EN_NUMERO,  CAN.EN_COMPLEMENTO,  CAN.EN_BAIRRO,  CAN.EN_MUNICIPIO,  CAN.NR_CEP,  
CAN.SG_UF,  CAN.NR_CPF,  CAN.DT_NASCIMENTO,  CAN.FL_STATUS,  CAN.CD_UNID_ADM,  CAN.DT_IMPORTACAO,  
CAN.NR_DIGITO_RG,  CAN.DT_ARQUIVO,  CAN.FL_ATIVO,  CAN.NR_FONE,  CAN.NM_EMAIL,  
TC.CD_CONCURSO AS TC_COD_CONCURSO,  TC.ANO_CONCURSO AS TC_ANO_CONCURSO, TC.DS_CONCURSO AS TC_DS_CONCURSO,  
TC.CD_GRAU AS TC_CD_GRAU 
FROM CESUH.DBO.TB_CANDIDATO CAN  
INNER JOIN CESUH.DBO.TB_CANDIDATO_CONCURSO CCON ON CAN.CD_CANDIDATO = CCON.CD_CANDIDATO  
INNER JOIN  CESUH.DBO.Tb_nota n ON n.cd_candidato = cAN.cd_candidato
INNER JOIN CESUH.DBO.TB_CONCURSO TC ON TC.CD_CONCURSO = CCON.CD_CONCURSO WHERE 1 = 1  
AND Upper(ds_sit_prova) = 'APROVADO'  
AND ISNULL(CAN.FL_ATIVO,'S') = 'S'   
AND (CAN.FL_ATIVO = 'S' OR CAN.FL_ATIVO IS NULL)  
AND UPPER(NM_CANDIDATO  collate sql_latin1_general_cp1251_ci_as) 
LIKE UPPER('%' + @NM_CANDIDATO + '%' collate sql_latin1_general_cp1251_ci_as) 
ORDER BY CAN.CD_CANDIDATO ;

--******************************************************************************
declare @NR_CPF varchar = '05505157980';
 SELECT distinct (CCON.CD_CONCURSO),  TC.DS_CONCURSO,  CAN.CD_CANDIDATO,  CAN.NM_CANDIDATO,  CAN.NM_MAE_CANDIDATO,  CAN.NR_RG,  CAN.SG_ORGAO_RG,  CAN.SG_UF_RG,  CAN.EN_CANDIDATO,  CAN.EN_NUMERO,  CAN.EN_COMPLEMENTO,  CAN.EN_BAIRRO,  CAN.EN_MUNICIPIO,  CAN.NR_CEP,  CAN.SG_UF,  CAN.NR_CPF,  CAN.DT_NASCIMENTO,  CAN.FL_STATUS,  CAN.CD_UNID_ADM,  CAN.DT_IMPORTACAO,  CAN.NR_DIGITO_RG,  CAN.DT_ARQUIVO,  CAN.FL_ATIVO,  CAN.NR_FONE,  CAN.NM_EMAIL,  TC.CD_CONCURSO AS TC_COD_CONCURSO,  TC.ANO_CONCURSO AS TC_ANO_CONCURSO, TC.DS_CONCURSO AS TC_DS_CONCURSO,  TC.CD_GRAU AS TC_CD_GRAU,  CER.NR_VISTO_CONFERE 
 FROM CESUH.DBO.TB_CANDIDATO CAN  
 INNER JOIN  CESUH.DBO.Tb_nota N ON N.cd_candidato = CAN.cd_candidato  
 INNER JOIN CESUH.DBO.TB_CANDIDATO_CONCURSO CCON ON CAN.CD_CANDIDATO = CCON.CD_CANDIDATO   
 INNER JOIN CESUH.DBO.TB_CONCURSO TC ON TC.CD_CONCURSO = CCON.CD_CONCURSO 
 LEFT JOIN CESUH.DBO.TB_CERTIFICADO CER ON CER.CD_CANDIDATO = CCON.CD_CANDIDATO 
 AND CCON.CD_CONCURSO = CER.CD_CONCURSO WHERE 1 = 1  
 AND ISNULL(CAN.FL_ATIVO,'S') = 'S'  
 AND (CAN.FL_ATIVO = 'S' OR CAN.FL_ATIVO IS NULL)  
 AND exists (select 0 from CESUH.DBO.Tb_nota n where n.cd_candidato = cAN.cd_candidato  AND Upper(ds_sit_prova) = 'APROVADO')   
 AND NR_CPF = @NR_CPF ORDER BY CAN.CD_CANDIDATO 

 --***********************

 select * from tb_candidato where nr_cpf ='22035587840'; 

 select  *  from CESUH.DBO.TB_CERTIFICADO CER where CER.CD_CANDIDATO = '9864074';  --  26690587878
 
 select top 10  *  from CESUH.DBO.TB_CERTIFICADO CER where CER.cd_tp_certificado = 2 ;
   

   SELECT TOP 1000 [CD_TP_CERTIFICADO]
      ,[DS_TP_CERTIFICADO]
  FROM [CESUH].[dbo].[TB_TIPO_CERTIFICADO]


  update  CESUH.DBO.TB_CERTIFICADO set NR_VISTO_CONFERE = '1848765824' WHERE CD_CERTIFICADO = 1527557;